---
apiVersion: v1
kind: Service
metadata:
  name: airport-service
  labels:
    app: airport-service
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v0
      kind: Mapping
      name: airports
      prefix: /
      service: airport-service:8000
      method: GET
spec:
  type: ClusterIP
  selector:
    app: airport-service
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8080
    name: http

---
apiVersion: v1
kind: ReplicationController
metadata:
  name: airport-service
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: airport-service
    spec:
      containers:
      - name: airport-service
        image: airports-assembly:1.0.1
        ports:
        - containerPort: 8000
        livenessProbe:
          httpGet:
            path: /health/live
            port: 8080
          initialDelaySeconds: 630
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /health/ready
            port: 8080
          initialDelaySeconds: 600
          timeoutSeconds: 5
