---
apiVersion: v1
kind: Service
metadata:
  name: country-service
  labels:
    app: country-service
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v0
      kind: Mapping
      name: countries
      prefix: /
      service: country-service:8000
      method: GET
spec:
  type: ClusterIP
  selector:
    app: country-service
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8080
    name: http

---
apiVersion: v1
kind: ReplicationController
metadata:
  name: country-service
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: country-service
    spec:
      containers:
      - name: country-service
        image: countries-assembly:1.0.1
        ports:
        - containerPort: 8000
        livenessProbe:
          httpGet:
            path: /health/live
            port: 8080
          initialDelaySeconds: 30
          timeoutSeconds: 1
        readinessProbe:
          httpGet:
            path: /health/ready
            port: 8080
          initialDelaySeconds: 15
          timeoutSeconds: 1
